/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author ltmer
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    private ArrayList<Card> pile = new ArrayList<Card>();
    
    private Deck d;
    private Player p1;
    private Player p2;
    
    private int score1;
    private int score2;
    
    private Card c1;
    private Card c2;
    
    boolean win;
    int turns;
    
    public Interface() {
        initComponents();
        jDraw.setVisible(false);
        jFinish.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jDraw = new javax.swing.JButton();
        deckLabel = new javax.swing.JLabel();
        card1Label = new javax.swing.JLabel();
        card2Label = new javax.swing.JLabel();
        jStart = new javax.swing.JButton();
        deckLabel1 = new javax.swing.JLabel();
        jP2 = new javax.swing.JLabel();
        jP1 = new javax.swing.JLabel();
        CP2 = new javax.swing.JLabel();
        CP1 = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        jFinish = new javax.swing.JButton();
        jPile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDraw.setText("Draw!");
        jDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrawActionPerformed(evt);
            }
        });
        jPanel3.add(jDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        deckLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        jPanel3.add(deckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        deckLabel.getAccessibleContext().setAccessibleName("deckLabel");

        card1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        jPanel3.add(card1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        card2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        jPanel3.add(card2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jStart.setText("START GAME");
        jStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartActionPerformed(evt);
            }
        });
        jPanel3.add(jStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));
        jStart.getAccessibleContext().setAccessibleName("");

        deckLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        jPanel3.add(deckLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jP2.setText("PLAYER 2");
        jPanel3.add(jP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jP1.setText("PLAYER 1");
        jPanel3.add(jP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        CP2.setText("Cards: 26");
        jPanel3.add(CP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        CP1.setText("Cards: 26");
        jPanel3.add(CP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result.setText("Good Luck!");
        Result.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, 30));

        jFinish.setText("Finish");
        jFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinishActionPerformed(evt);
            }
        });
        jPanel3.add(jFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPile.setText("Pile Size: 0");
        jPanel3.add(jPile, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 380, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrawActionPerformed

        //get the top card from each players hand
        c1 = p1.getTopCard();
        c2 = p2.getTopCard();
        
        //Set images to current cards
        card1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(c1.getImage())));
        card2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(c2.getImage())));
        
        //Get card values for comparison
        score1 = c1.getValue();
        score2 = c2.getValue();
        
        //Compare cards and show result
        if(score1>score2){
            
            //Adds cards from current turn to player 1's hand
            p1.addCard(c2);
            p1.addCard(c1);
            
            //Adds cards from tie pile to player 1's hand
            while(!pile.isEmpty()){
                p1.addCard(pile.remove(0));      
            }
            
            //displays result of round
            Result.setText("Player 1 Wins This Round!");
            
        }else if(score2>score1){
            
            //Adds cards from current turn to player 2's hand
            p2.addCard(c1);
            p2.addCard(c2);
            
            //Adds cards from tie pile to player 2's hand
            while(!pile.isEmpty()){
                p2.addCard(pile.remove(0));      
            }
            
            //displays result of round
            Result.setText("Player 2 Wins This Round!");
            
        }else{
            
            //Adds cards to Tie pile and displays result of round
            pile.add(c1);
            pile.add(c2);
            Result.setText("TIE!");
        }
         
        //Display the size of player hands and pile size
        CP1.setText("Cards: " + p1.handSize());
        CP2.setText("Cards: " + p2.handSize());
        jPile.setText("Pile Size: " + pile.size());
        
        //Check if player has won, dispay winner
        if(p1.handSize()==0){
            Result.setText("Player 2 Wins The Game!!!!");
            jDraw.setVisible(false);
            jStart.setVisible(true);
            jFinish.setVisible(false);
            win=true;
        }else if(p2.handSize()==0){
            Result.setText("Player 1 Wins The Game!!!!");
            jDraw.setVisible(false);
            jStart.setVisible(true);
            jFinish.setVisible(false);
            win=true;
        }
        
    }//GEN-LAST:event_jDrawActionPerformed

    private void jStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartActionPerformed
        
        //set Card Icons back to facedown
        card1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b2fv.png")));
        card2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b2fv.png")));
            
        //Create and shuffle deck
        d = new Deck();
        d.shuffle();
       
        //Create player objects
        p1 = new Player();
        p2 = new Player();
                
        //Populate player hands
        for(int i=0; i<=25; i++){
            
            c1 = d.getTopCard();
            c2 = d.getTopCard();
            
            p1.addCard(c1);
            p2.addCard(c2);
              
        }
        
        //Set text for inital card count
        CP1.setText("Cards: 26");
        CP2.setText("Cards: 26");
        Result.setText("Good Luck!");
        
        //Hide the start button and show the Draw button
        jDraw.setVisible(true);
        jStart.setVisible(false);
        jFinish.setVisible(true);
        
        //Clean up before game starts
        d = null;
        c1 = null;
        c2 = null;
        pile.clear();
        
    }//GEN-LAST:event_jStartActionPerformed
//Finishes game
    private void jFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinishActionPerformed
        
        win=false;
        
        //Draws until game is over
        while(win == false){      
            jDraw.doClick(10);
        }
        
    }//GEN-LAST:event_jFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CP1;
    private javax.swing.JLabel CP2;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel card1Label;
    private javax.swing.JLabel card2Label;
    private javax.swing.JLabel deckLabel;
    private javax.swing.JLabel deckLabel1;
    private javax.swing.JButton jDraw;
    private javax.swing.JButton jFinish;
    private javax.swing.JLabel jP1;
    private javax.swing.JLabel jP2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPile;
    private javax.swing.JButton jStart;
    // End of variables declaration//GEN-END:variables
}
